# baseURL = "https://pablogs.dev/"
baseURL = 'https://example.org/'
title = "Void *Pablogs" # Cambia esto por el nombre que elijas
theme = "PaperMod"      # Ajusta según el tema que instales

# 1. Configuración de Taxonomías
# Aquí le decimos a Hugo que queremos usar 'series' además de los clásicos 'tags' y 'categories'
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

# 2. Configuración Multilenguaje (i18n)
defaultContentLanguage = "en"

[languages]
  # Configuración para INGLÉS (Por defecto)
  [languages.en]
    languageName = "English"
    weight = 1
    title = "Void *Pablogs"
    # Puedes añadir parámetros específicos del idioma, útiles para SEO
    [languages.en.params]
      description = "A blog about C programming, low-level concepts, and systems engineering."

	[languages.en.params.homeInfoParams]
		Title = "Hi there! I'm Pablo 👋"
		Content = "Welcome to my blog. Here I document my journey writing C, building custom memory allocators, and exploring low-level systems programming."

	[[languages.en.params.socialIcons]]
		name = "github"
		url = "https://github.com/ansuzgs"
	[[languages.en.params.socialIcons]]
		name = "linkedin"
		url = "https://linkedin.com/in/pablogonzalez21191/"

  # Configuración para ESPAÑOL
  [languages.es]
    languageName = "Español"
    weight = 2
    title = "Void *Pablogs (ES)"
    [languages.es.params]
      description = "Un blog sobre programación en C, bajo nivel y desarrollo de sistemas."

	[languages.es.params.homeInfoParams]
		Title = "¡Hola! Soy Pablo 👋"
		Content = "Bienvenido a mi blog. Aquí documento mis proyectos en C, la creación de allocators de memoria y la programación de sistemas a bajo nivel."

	[[languages.es.params.socialIcons]]
		name = "github"
		url = "https://github.com/ansuzgs"
	[[languages.es.params.socialIcons]]
		name = "linkedin"
		url = "https://linkedin.com/in/pablogonzalez21191/"
